import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    home: 'Home',
    trash: 'Trash',
    feedback: 'Feedback',
    settings: 'Settings',
    profile: 'Profile',
    logout: 'Log Out',
    welcome: 'Welcome to Vietnote',
    myNotes: 'My Notes',
    searchPlaceholder: 'Search notes...',
    noNotes: 'No notes yet',
    createFirst: 'Create your first note to get started',
    trashEmpty: 'Trash is empty',
    noDeletedNotes: 'No deleted notes here',
    appearance: 'Appearance',
    appearanceDesc: 'Choose your preferred color scheme',
    language: 'Language',
    languageDesc: 'Select your preferred language',
    settingsDesc: 'Customize your experience',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    submit: 'Submit',
    cancel: 'Cancel',
    restore: 'Restore',
    delete: 'Delete',
    deletePermanently: 'Delete Permanently',
    email: 'Email',
    senderName: 'Your Name',
    subject: 'Subject',
    message: 'Message',
    feedbackTitle: 'Send us your feedback',
    feedbackDesc: "We'd love to hear your thoughts and suggestions",
    success: 'Success!',
    feedbackSent: 'Your feedback has been sent successfully. Thank you!',
    error: 'Error',
    required: 'This field is required',
    invalidEmail: 'Please enter a valid email address',
    minLength: 'Must be at least {min} characters',
    restoreConfirm: 'Are you sure you want to restore this note?',
    deleteConfirm: 'Are you sure? This action cannot be undone.',
    restored: 'Note restored successfully',
    deleted: 'Note deleted permanently',
    ok: 'OK',
    notesCount: '{count} notes',
    deletedOn: 'Deleted on',
    updatedAgo: 'Updated {time} ago',
    just_now: 'just now',
    minutes: '{n}m',
    hours: '{n}h',
    days: '{n}d',
    newNoteTitlePlaceholder: 'Enter a title...',
    newNoteContentPlaceholder: 'Start writing your note...',
    searchInNote: 'Search in note...',
    pinned: 'Note pinned!',
    unpinned: 'Note unpinned!',
    personalInfo: 'Personal Information',
    personalInfoDesc: 'Update your personal details here',
    fullName: 'Full Name',
    username: 'Username (Email)',
    age: 'Age',
    gender: 'Gender',
    edit: 'Edit',
    save: 'Save',
    dangerZone: 'Danger Zone',
    dangerZoneDesc: 'Manage your account security',
    changePassword: 'Change Password',
    deleteAccount: 'Delete Account',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    profileUpdated: 'Profile updated successfully!',
    deleteAccountConfirm:
      'Are you sure you want to delete your account? This is irreversible.',
    login: 'Login',
    register: 'Register',
    loginTitle: 'Welcome back!',
    loginDesc: 'Login to access your notes.',
    registerTitle: 'Create an Account',
    registerDesc: 'Join us and start taking notes.',
    password: 'Password',
    loginWithGoogle: 'Continue with Google',
    loginWithGithub: 'Continue with Github',
    or: 'OR',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    usernameIsEmail: 'Your username is your @gmail.com address',
    invalidGmail: 'Username must be a valid @gmail.com address',
    loginFailed: 'Login Failed',
    invalidCredentials: 'Invalid username or password',
    forgotPassword: 'Forgot Password?',
    forgotPasswordTitle: 'Reset Password',
    forgotPasswordDesc: 'Enter your email to receive a reset link',
    sendResetLink: 'Send Reset Link',
    backToLogin: 'Back to Login',
    resetEmailSent: 'Reset link sent to your email!',
    pageNotFound: 'Page Not Found',
    backToHome: 'Back to Home',
    noCorrectOTP: 'Incorrect or expired verification code.',
    notCorrectPassword: 'Incorrect password.',
    donePasswordChange:
      'Password changed successfully. Do you want to log in now?',
    go: 'Go now',
    typeOTP: 'Enter the verification code sent to your email',
    restorePassword: 'Restore Password',
    typeNewPassword: 'Enter new password',
    OTPSent: 'Verification code sent to your email.',
    isSending: 'Sending...',
    sendOTP: 'Send OTP',
    continue: 'Continue',
    back: 'Back',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    updateProfileFailed: 'Failed to update profile.',
    updateProfileSuccess: 'Profile updated successfully!',
    currentPassword: 'Current Password',
    newPasswordConfirm: 'Confirm New Password',
    passwordChanged: 'Password changed successfully.',
    deleteAccountSuccess: 'Your account has been deleted.',
    deleteAccountFailed: 'Failed to delete account.',
    changePasswordFailed: 'Failed to change password.',
    passwordMinLength: 'At least {min} characters',
    enterCurrentPassword: 'Enter current password',
    enterNewPassword: 'Enter new password',
    enterNewPasswordConfirm: 'Confirm new password',
    deleteAccountWarning:
      'This action cannot be undone. This will permanently delete your account and all associated data.',
    typeToConfirm: 'Please type "{match}" to confirm.',
    confirmDelete: 'I understand, delete this account',
  },
  vi: {
    home: 'Trang chủ',
    trash: 'Thùng rác',
    feedback: 'Phản hồi',
    settings: 'Cài đặt',
    profile: 'Hồ sơ',
    logout: 'Đăng xuất',
    welcome: 'Chào mừng đến Vietnote',
    myNotes: 'Ghi chú của tôi',
    searchPlaceholder: 'Tìm kiếm ghi chú...',
    noNotes: 'Chưa có ghi chú',
    createFirst: 'Tạo ghi chú đầu tiên để bắt đầu',
    trashEmpty: 'Thùng rác trống',
    noDeletedNotes: 'Không có ghi chú nào bị xóa',
    appearance: 'Giao diện',
    appearanceDesc: 'Chọn bảng màu ưa thích của bạn',
    language: 'Ngôn ngữ',
    languageDesc: 'Chọn ngôn ngữ ưa thích của bạn',
    settingsDesc: 'Tùy chỉnh trải nghiệm của bạn',
    lightMode: 'Sáng',
    darkMode: 'Tối',
    submit: 'Gửi',
    cancel: 'Hủy',
    restore: 'Khôi phục',
    delete: 'Xóa',
    deletePermanently: 'Xóa vĩnh viễn',
    email: 'Email',
    senderName: 'Tên của bạn',
    subject: 'Tiêu đề',
    message: 'Nội dung',
    feedbackTitle: 'Gửi phản hồi cho chúng tôi',
    feedbackDesc: 'Chúng tôi rất muốn nghe ý kiến và đề xuất của bạn',
    success: 'Thành công!',
    feedbackSent: 'Phản hồi của bạn đã được gửi thành công. Cảm ơn bạn!',
    error: 'Lỗi',
    required: 'Trường này là bắt buộc',
    invalidEmail: 'Vui lòng nhập email hợp lệ',
    minLength: 'Phải có ít nhất {min} ký tự',
    restoreConfirm: 'Bạn có chắc muốn khôi phục ghi chú này?',
    deleteConfirm: 'Bạn có chắc chắn? Hành động này không thể hoàn tác.',
    restored: 'Đã khôi phục ghi chú thành công',
    deleted: 'Đã xóa ghi chú vĩnh viễn',
    ok: 'OK',
    notesCount: '{count} ghi chú',
    deletedOn: 'Đã xóa vào',
    updatedAgo: 'Cập nhật {time} trước',
    just_now: 'vừa xong',
    minutes: '{n} phút',
    hours: '{n} giờ',
    days: '{n} ngày',
    newNoteTitlePlaceholder: 'Hãy nhập nội dung (title)',
    newNoteContentPlaceholder: 'Bắt đầu viết ghi chú của bạn...',
    searchInNote: 'Tìm trong ghi chú...',
    pinned: 'Đã ghim ghi chú!',
    unpinned: 'Đã bỏ ghim ghi chú!',
    personalInfo: 'Thông tin cá nhân',
    personalInfoDesc: 'Cập nhật chi tiết cá nhân của bạn tại đây',
    fullName: 'Họ và Tên',
    username: 'Tên người dùng (Email)',
    age: 'Tuổi',
    gender: 'Giới tính',
    edit: 'Chỉnh sửa',
    save: 'Lưu',
    dangerZone: 'Khu vực nguy hiểm',
    dangerZoneDesc: 'Quản lý bảo mật tài khoản của bạn',
    changePassword: 'Đổi mật khẩu',
    deleteAccount: 'Xóa tài khoản',
    male: 'Nam',
    female: 'Nữ',
    other: 'Khác',
    profileUpdated: 'Cập nhật hồ sơ thành công!',
    deleteAccountConfirm:
      'Bạn có chắc muốn xóa tài khoản? Hành động này không thể hoàn tác.',
    login: 'Đăng nhập',
    register: 'Đăng ký',
    loginTitle: 'Chào mừng trở lại!',
    loginDesc: 'Đăng nhập để truy cập ghi chú của bạn.',
    registerTitle: 'Tạo tài khoản',
    registerDesc: 'Tham gia và bắt đầu ghi chú.',
    password: 'Mật khẩu',
    loginWithGoogle: 'Tiếp tục với Google',
    loginWithGithub: 'Tiếp tục với Github',
    or: 'HOẶC',
    dontHaveAccount: 'Chưa có tài khoản?',
    alreadyHaveAccount: 'Đã có tài khoản?',
    usernameIsEmail: 'Tên người dùng là địa chỉ @gmail.com của bạn',
    invalidGmail: 'Tên người dùng phải là địa chỉ @gmail.com hợp lệ',
    loginFailed: 'Đăng nhập thất bại',
    invalidCredentials: 'Tên đăng nhập hoặc mật khẩu không đúng',
    forgotPassword: 'Quên mật khẩu?',
    forgotPasswordTitle: 'Đặt lại mật khẩu',
    forgotPasswordDesc: 'Nhập email để nhận liên kết đặt lại',
    sendResetLink: 'Gửi liên kết khôi phục',
    backToLogin: 'Quay lại đăng nhập',
    resetEmailSent: 'Liên kết đặt lại đã được gửi đến email của bạn!',
    pageNotFound: 'Không tìm thấy trang',
    backToHome: 'Về trang chủ',
    noCorrectOTP: 'Mã xác nhận không đúng hoặc đã hết hạn.',
    notCorrectPassword: 'Mật khẩu không đúng.',
    donePasswordChange:
      'Đã đổi mật khẩu thành công. Bạn có muốn đăng nhập ngay không?',
    go: 'Vào luôn',
    typeOTP: 'Nhập mã xác nhận đã gửi đến email của bạn',
    restorePassword: 'Khôi phục mật khẩu',
    typeNewPassword: 'Nhập mật khẩu mới',
    OTPSent: 'Mã xác nhận đã được gửi đến email của bạn.',
    isSending: 'Đang gửi...',
    sendOTP: 'Gửi mã OTP',
    continue: 'Tiếp tục',
    back: 'Quay lại',
    newPassword: 'Mật khẩu mới',
    confirmPassword: 'Xác nhận mật khẩu',
    updateProfileFailed: 'Cập nhật hồ sơ thất bại.',
    updateProfileSuccess: 'Cập nhật hồ sơ thành công!',
    currentPassword: 'Mật khẩu hiện tại',
    newPasswordConfirm: 'Xác nhận mật khẩu mới',
    passwordChanged: 'Đổi mật khẩu thành công.',
    deleteAccountSuccess: 'Tài khoản đã bị xóa vĩnh viễn.',
    deleteAccountFailed: 'Không thể xóa tài khoản. Vui lòng thử lại.',
    changePasswordFailed: 'Đổi mật khẩu thất bại.',
    passwordMinLength: 'Ít nhất {min} ký tự',
    enterCurrentPassword: 'Nhập mật khẩu cũ',
    enterNewPassword: 'Nhập mật khẩu mới',
    enterNewPasswordConfirm: 'Xác nhận mật khẩu mới',
    deleteAccountWarning:
      'Hành động này không thể hoàn tác. Việc này sẽ xóa vĩnh viễn tài khoản và tất cả dữ liệu liên quan.',
    typeToConfirm: 'Vui lòng gõ "{match}" để xác nhận.',
    confirmDelete: 'Tôi hiểu, xóa tài khoản này',
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(
    () => localStorage.getItem('vietnote-language') || 'en',
  );

  useEffect(() => {
    localStorage.setItem('vietnote-language', language);
  }, [language]);

  const t = (key, params = {}) => {
    let text = translations[language][key] || key;
    Object.keys(params).forEach((param) => {
      text = text.replace(`{${param}}`, params[param]);
    });
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
